baseURL = 'http://ensamblecoffee.cl/'
languageCode = 'en-us'
title = 'Ensamble-Cafe'
theme = 'hugo-PaperMod'


[menu]
[[menu.main]]
  identifier = 'Acerca'
  name = 'Acerca'
  url = '/acerca/'
  weight = 20
[[menu.main]]
  name = 'Inicio'
  url = '/'
  weight = 10

